spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoices
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  batch:
    job:
      enabled: false # Desativa a execução automática de jobs na inicialização
    jdbc:
      initialize-schema: always
