INSERT INTO CONTAS (status, data_fechamento) VALUES ('ABERTA', EXTRACT(DAY FROM CURRENT_DATE));
INSERT INTO CONTAS (status, data_fechamento) VALUES ('ABERTA', EXTRACT(DAY FROM CURRENT_DATE));
INSERT INTO CONTAS (status, data_fechamento) VALUES ('ABERTA', EXTRACT(DAY FROM CURRENT_DATE));
INSERT INTO CONTAS (status, data_fechamento) VALUES ('ABERTA', EXTRACT(DAY FROM CURRENT_DATE));
