CREATE TABLE BATCH_PARTITION_QUEUE (
    ID BIGSERIAL PRIMARY KEY,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    PARTITION_ID INT NOT NULL,
    STATUS VARCHAR(25) NOT NULL, -- PENDING, CLAIMED, COMPLETED, FAILED
    WORKER_POD_ID VARCHAR(255),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP
);
